### ISSUE TITLE
undefined method `get_access_token'

### ISSUE THREAD

**Issue by fieldly** [my-codeworks/fortnox-api#1] opened 2015-02-27 15:26 UTC
Hello,

I try to use your gem but I get this when I try to use it:

NoMethodError - undefined method `get_access_token' for Fortnox::API:Module:
Also I have required 'fortnox/api' into the service object ('fortnox-api' was not found).

Any idea what is wrong?

**Comment by d-Pixie** [comment] 2015-04-07 07:09
Sorry for the very long delay @fieldly, I had an old email as the default for notifications, fixed now.

Yes, the problem is that this gem is very much under construction. I posted my latest changes the other day, but it's still in the middle of a spike and not in working order unfortunately.

If you want to contribute we could go through the basic structure of the gem and get you going in short order. The only thing not working at the moment is some conflict with Adamantium and copying objects on change, so I could probably fix that in a day or so.

If you can't, or don't want to, code I'm sorry to say that you will just have to wait until I find the time to move it along on my own. And that will probably be another month or so considering my current workload :/ I'll try to negotiate with my employer, Fortnox, about getting some time to work on this during my normal office hours, but there is no guarantee that they will like it. Right now, and if they don't, this is a purely hobby project for me.

**Comment by ehannes** [comment] 2016-01-13 14:05
@d-Pixie I'm about to build a Rails app that will be using the Fortnox API a lot and found this repo. But I guess your employer didn't let you work on this during normal office hours and that it's a "purely hobby project", right?

**Comment by d-Pixie** [comment] 2016-01-13 14:57
Yeah, that is unfortunately right. Though it was at the point of working for customers when I left off.

If you are interested @ehannes I would definately be up for putting some more work into it.

**Comment by ehannes** [comment] 2016-01-13 15:01
@d-Pixie maybe we can get in touch by mail?

**Comment by d-Pixie** [comment] 2016-01-13 15:06
Sure @ehannes, you can get me at jonas.schubert.erlandsson@gmail.com or Skype at jonas.erlandsson or I could invite you to a Slack room, if you happen to like Slack and I get your email :)

**Comment by d-Pixie** [comment] 2016-01-20 11:21
This issue is solved with the recent updates to the gem. If you are still having problems please open a new issue and describe the new problem there :)

**Closed by d-Pixie** 2016-01-20 11:21 UTC
